### ISSUE TITLE
"Detected out of order event.step likely caused by a TensorFlow restart"

### ISSUE THREAD

**Issue by liavkoren** [teffland/pytorch-monitor#15]
I don't know if this is a monitor issue or tensorboard-x or my code or ??? 

I get a *lot* of these warnings. Right now the code is in a notebook which is kind of a mess, I can try and see if I can make a minimal example if you'd like.

**Comment by teffland** [comment]
Sorry I don't quite follow. These are warnings coming from tensorboard when you run from command line?

Are you unable to view the logs because of this error? Either way this would be an issue with the interaction of tensorboardX and tensorboard

**Comment by liavkoren** [comment]
Yes, they're console warnings. I'll follow up with TBX, if they're the right people to talk to about this.
